//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeBox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrimeBox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _9029802_1363467705523 {
            get {
                object obj = ResourceManager.GetObject("9029802-1363467705523", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Antique_wallpapers_440 {
            get {
                object obj = ResourceManager.GetObject("Antique_wallpapers_440", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cloudsscroll {
            get {
                object obj = ResourceManager.GetObject("cloudsscroll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cooltext1004031883 {
            get {
                object obj = ResourceManager.GetObject("cooltext1004031883", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cooltext1004033544 {
            get {
                object obj = ResourceManager.GetObject("cooltext1004033544", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cooltext10040335441 {
            get {
                object obj = ResourceManager.GetObject("cooltext10040335441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cooltext1004035202 {
            get {
                object obj = ResourceManager.GetObject("cooltext1004035202", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cooltext1004038088 {
            get {
                object obj = ResourceManager.GetObject("cooltext1004038088", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cooltext1004038402 {
            get {
                object obj = ResourceManager.GetObject("cooltext1004038402", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cutcaster_photo_100454592_Historic_Parchment_Scroll_Background {
            get {
                object obj = ResourceManager.GetObject("cutcaster-photo-100454592-Historic-Parchment-Scroll-Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grid_icon {
            get {
                object obj = ResourceManager.GetObject("grid-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kitchen_List_ingredients_icon {
            get {
                object obj = ResourceManager.GetObject("Kitchen-List-ingredients-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Math_problems_dyscalculia {
            get {
                object obj = ResourceManager.GetObject("Math-problems-dyscalculia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap math_reasoning {
            get {
                object obj = ResourceManager.GetObject("math_reasoning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nature_backgrounds____381913 {
            get {
                object obj = ResourceManager.GetObject("nature_backgrounds___-381913", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prime_number_generator {
            get {
                object obj = ResourceManager.GetObject("prime-number-generator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prime_number_generator1 {
            get {
                object obj = ResourceManager.GetObject("prime-number-generator1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slqsm {
            get {
                object obj = ResourceManager.GetObject("slqsm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tabs_iphone_hd_wallpaper_iphonewallpaperhi_com_584_320x480 {
            get {
                object obj = ResourceManager.GetObject("tabs-iphone-hd-wallpaper-iphonewallpaperhi.com-584-320x480", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Timeline_List_Grid_Grid_icon {
            get {
                object obj = ResourceManager.GetObject("Timeline-List-Grid-Grid-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Timeline_List_Grid_List_icon {
            get {
                object obj = ResourceManager.GetObject("Timeline-List-Grid-List-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Timeline_List_Grid_Timeline_icon {
            get {
                object obj = ResourceManager.GetObject("Timeline-List-Grid-Timeline-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wallpaper_114675275 {
            get {
                object obj = ResourceManager.GetObject("wallpaper_114675275", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wallpaper_fall_1024 {
            get {
                object obj = ResourceManager.GetObject("wallpaper_fall_1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wallpaper_fall_10241 {
            get {
                object obj = ResourceManager.GetObject("wallpaper_fall_10241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
